name: build and push to dockerhub

on:
  push:
    branches:
      - master
      - feature/*
  pull_request: 

jobs:
  push_to_registry:
    uses: .github/workflows/build.yml@feature/mount_env_variables
    # without this it cannot login to the registry
    secrets: inherit
